name: Update Banner Version

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-banner:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get latest release version
      id: get_version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
        if [ "$VERSION" = "null" ] || [ -z "$VERSION" ]; then
          VERSION="v1.0.0"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Latest version: $VERSION"
    
    - name: Update banner and create PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Setup git
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Create branch
        BRANCH_NAME="update-banner-$(date +%s)"
        git checkout -b $BRANCH_NAME
        
        # Update banner
        sed -i "s|<text x=\"100\" y=\"250\"[^>]*>[^<]*</text>|<text x=\"100\" y=\"250\" text-anchor=\"middle\" font-family=\"monospace\" font-size=\"16\" fill=\"#00FF00\">${{ steps.get_version.outputs.VERSION }}</text>|g" assets/banner.svg
        
        # Commit and push
        git add assets/banner.svg
        git commit -m "chore: update banner version to ${{ steps.get_version.outputs.VERSION }}"
        git push origin $BRANCH_NAME
        
        # Create PR
        gh pr create \
          --title "chore: update banner version to ${{ steps.get_version.outputs.VERSION }}" \
          --body "Automated update of banner version" \
          --base main \
          --head $BRANCH_NAME